package com.klikcalendar.app.strings

enum class Language {
    Chinese,
    English,
}

data class AppStrings(
    val schedule: String,
    val records: String,
    val workLife: String,
    val operations: String,
    val quickActions: String,
    val confirm: String,
    val cancel: String,
    val applyFilters: String,
    val battery: String,
    val bluetooth: String,
    val recording: String,
    val network: String,
    val sensors: String,
    val sync: String,
    val lastSync: String,
    val miniApps: String,
    val criticalAlerts: String,
    val attention: String,
    val timeline: String,
    val pipeline: String,
    val addMeeting: String,
    val addDevice: String,
    val captureNotes: String,
    val runAutomation: String,
    val addTask: String,
    val knowledgeGraph: String,
    val statusBoard: String,
    val pending: String,
    val approved: String,
    val declined: String,
    val archived: String,
    val swipeForActions: String,
    val filterHeader: String,
    val filtersReset: String,
    val insights: String,
    val languageToggle: String,
    val feedback: String,
    val meetingDetails: String,
    val noLinkedContent: String,
    val openMiniApp: String,
)

val englishStrings = AppStrings(
    schedule = "Schedule",
    records = "Transcripts",
    workLife = "Work Life",
    operations = "Operations",
    quickActions = "Quick Actions",
    confirm = "Confirm",
    cancel = "Cancel",
    applyFilters = "Apply Filters",
    battery = "Battery",
    bluetooth = "BLE",
    recording = "Recording",
    network = "Network",
    sensors = "Sensors",
    sync = "Sync",
    lastSync = "Last sync",
    miniApps = "Mini Apps",
    criticalAlerts = "Critical Alerts",
    attention = "Needs Attention",
    timeline = "Timeline",
    pipeline = "Pipeline",
    addMeeting = "Log Meeting",
    addDevice = "Register Device",
    captureNotes = "Capture Notes",
    runAutomation = "Run Automation",
    addTask = "New Task",
    knowledgeGraph = "Knowledge Graph",
    statusBoard = "Status Board",
    pending = "Pending",
    approved = "Approved",
    declined = "Declined",
    archived = "Archived",
    swipeForActions = "Swipe for contextual actions",
    filterHeader = "Filters",
    filtersReset = "Reset",
    insights = "Insights",
    languageToggle = "中 / EN",
    feedback = "Feedback",
    meetingDetails = "Meeting Detail",
    noLinkedContent = "No linked content yet",
    openMiniApp = "Open Mini App",
)

val chineseStrings = AppStrings(
    schedule = "日程",
    records = "转录",
    workLife = "Work Life",
    operations = "运营",
    quickActions = "快速操作",
    confirm = "确认",
    cancel = "取消",
    applyFilters = "应用筛选",
    battery = "电量",
    bluetooth = "蓝牙",
    recording = "录音",
    network = "网络",
    sensors = "感应器",
    sync = "同步",
    lastSync = "上次同步",
    miniApps = "Mini Apps",
    criticalAlerts = "高优告警",
    attention = "待处理",
    timeline = "时间线",
    pipeline = "流程线",
    addMeeting = "记录会议",
    addDevice = "登记设备",
    captureNotes = "语音摘要",
    runAutomation = "执行自动化",
    addTask = "新建任务",
    knowledgeGraph = "知识图谱",
    statusBoard = "状态面板",
    pending = "待定",
    approved = "已确认",
    declined = "已拒绝",
    archived = "已归档",
    swipeForActions = "左右滑动调用操作",
    filterHeader = "筛选",
    filtersReset = "重置",
    insights = "洞察",
    languageToggle = "中 / EN",
    feedback = "反馈",
    meetingDetails = "会议详情",
    noLinkedContent = "暂无关联内容",
    openMiniApp = "打开 Mini App",
)

fun strings(language: Language): AppStrings =
    when (language) {
        Language.Chinese -> chineseStrings
        Language.English -> englishStrings
    }
